#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/api.jar:$APPDIR/lib/FlickrEvents.jar:$APPDIR/lib/core.jar:$APPDIR/lib/gifAnimation.jar:$APPDIR/lib/gifAnimation.jar" FlickrEvents
